### ISSUE TITLE
{"error":"Internal Server Error"}

### ISSUE THREAD

**Issue by gabriel-logan** [Judge-Paul/playlist-pro#23]
When I try to download all mp3.zip this error occurs, I tested that downloading some songs individually also presented errors

![image](https://github.com/Judge-Paul/playlist-pro/assets/96627244/a401a492-b32b-4593-8baf-b9d580c4a99b)

**Comment by Judge-Paul** [comment]
Can you send me the playlist you're trying to download, I'll look into it and see if I can make a fix
